app:
  port: 3003
  site:
    brand: PROOF
    logo: "/img/poex-logo-white.svg"
    title: Proof of Existence
    slogan: The original Blockchain notary service
    tagline: Instant & secure Proof of Existence for any document
    email: love@proofofexistence.com
    keywords:
      - blockchain
      - notary
      - proof of existence
      - bitcoin
      - p2p
      - anonymous
      - secure
      - permanent
      - distributed
      - documents
      - agreements
      - contracts

social:
  twitter: proofxstence
  facebook: proofxstence
  github: proofofexistence

services:
  insight:
    mainnet:
      url: https://insight.bitpay.com
      api: /api
    testnet:
      url: https://test-insight.bitpay.com
      api: /api

nodemailer:
  options:
    service: Gmail
