app:
  port: 3003
  site:
    title: Proof of Existence
    description: >-
      The original Blockchain notary service. Instant & secure Proof of
      Existence for any document.

services:
  blockcypher:
    url: https://api.blockcypher.com/v1

nodemailer:
  options:
    service: Gmail
