app:
  port: 3003
  site:
    title: Proof of Existence
    slogan: The original Blockchain notary service
    tagline: Instant & secure Proof of Existence for any document
    keywords:
      - blockchain
      - notary
      - proof of existence
      - bitcoin
      - p2p
      - anonymous
      - secure
      - permanent
      - distributed
      - documents
      - agreements
      - contracts

services:
  blockcypher:
    url: https://api.blockcypher.com/v1

nodemailer:
  options:
    service: Gmail
